# Generated by Django 5.2.7 on 2025-11-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_alter_staffs_fcm_token_alter_students_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
